# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\clementfrancois\Documents\SpaceBattle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\clementfrancois\Documents\SpaceBattle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\clementfrancois\Documents\SpaceBattle\CMakeFiles C:\Users\clementfrancois\Documents\SpaceBattle\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\clementfrancois\Documents\SpaceBattle\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) -f CMakeFiles\googletest.dir\build.make CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

#=============================================================================
# Target rules for targets named space_battle_server_test

# Build rule for target.
space_battle_server_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 space_battle_server_test
.PHONY : space_battle_server_test

# fast build rule for target.
space_battle_server_test/fast:
	$(MAKE) -f CMakeFiles\space_battle_server_test.dir\build.make CMakeFiles/space_battle_server_test.dir/build
.PHONY : space_battle_server_test/fast

#=============================================================================
# Target rules for targets named protocole_test

# Build rule for target.
protocole_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 protocole_test
.PHONY : protocole_test

# fast build rule for target.
protocole_test/fast:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/build
.PHONY : protocole_test/fast

external/googletest/googletest/src/gtest-all.obj: external/googletest/googletest/src/gtest-all.cc.obj

.PHONY : external/googletest/googletest/src/gtest-all.obj

# target to build an object file
external/googletest/googletest/src/gtest-all.cc.obj:
	$(MAKE) -f CMakeFiles\googletest.dir\build.make CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest-all.cc.obj
.PHONY : external/googletest/googletest/src/gtest-all.cc.obj

external/googletest/googletest/src/gtest-all.i: external/googletest/googletest/src/gtest-all.cc.i

.PHONY : external/googletest/googletest/src/gtest-all.i

# target to preprocess a source file
external/googletest/googletest/src/gtest-all.cc.i:
	$(MAKE) -f CMakeFiles\googletest.dir\build.make CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest-all.cc.i
.PHONY : external/googletest/googletest/src/gtest-all.cc.i

external/googletest/googletest/src/gtest-all.s: external/googletest/googletest/src/gtest-all.cc.s

.PHONY : external/googletest/googletest/src/gtest-all.s

# target to generate assembly for a file
external/googletest/googletest/src/gtest-all.cc.s:
	$(MAKE) -f CMakeFiles\googletest.dir\build.make CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest-all.cc.s
.PHONY : external/googletest/googletest/src/gtest-all.cc.s

external/googletest/googletest/src/gtest_main.obj: external/googletest/googletest/src/gtest_main.cc.obj

.PHONY : external/googletest/googletest/src/gtest_main.obj

# target to build an object file
external/googletest/googletest/src/gtest_main.cc.obj:
	$(MAKE) -f CMakeFiles\googletest.dir\build.make CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest_main.cc.obj
.PHONY : external/googletest/googletest/src/gtest_main.cc.obj

external/googletest/googletest/src/gtest_main.i: external/googletest/googletest/src/gtest_main.cc.i

.PHONY : external/googletest/googletest/src/gtest_main.i

# target to preprocess a source file
external/googletest/googletest/src/gtest_main.cc.i:
	$(MAKE) -f CMakeFiles\googletest.dir\build.make CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest_main.cc.i
.PHONY : external/googletest/googletest/src/gtest_main.cc.i

external/googletest/googletest/src/gtest_main.s: external/googletest/googletest/src/gtest_main.cc.s

.PHONY : external/googletest/googletest/src/gtest_main.s

# target to generate assembly for a file
external/googletest/googletest/src/gtest_main.cc.s:
	$(MAKE) -f CMakeFiles\googletest.dir\build.make CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest_main.cc.s
.PHONY : external/googletest/googletest/src/gtest_main.cc.s

protocol/src/Net.obj: protocol/src/Net.cpp.obj

.PHONY : protocol/src/Net.obj

# target to build an object file
protocol/src/Net.cpp.obj:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/src/Net.cpp.obj
.PHONY : protocol/src/Net.cpp.obj

protocol/src/Net.i: protocol/src/Net.cpp.i

.PHONY : protocol/src/Net.i

# target to preprocess a source file
protocol/src/Net.cpp.i:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/src/Net.cpp.i
.PHONY : protocol/src/Net.cpp.i

protocol/src/Net.s: protocol/src/Net.cpp.s

.PHONY : protocol/src/Net.s

# target to generate assembly for a file
protocol/src/Net.cpp.s:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/src/Net.cpp.s
.PHONY : protocol/src/Net.cpp.s

protocol/src/NetIOBusinessData.obj: protocol/src/NetIOBusinessData.cpp.obj

.PHONY : protocol/src/NetIOBusinessData.obj

# target to build an object file
protocol/src/NetIOBusinessData.cpp.obj:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/src/NetIOBusinessData.cpp.obj
.PHONY : protocol/src/NetIOBusinessData.cpp.obj

protocol/src/NetIOBusinessData.i: protocol/src/NetIOBusinessData.cpp.i

.PHONY : protocol/src/NetIOBusinessData.i

# target to preprocess a source file
protocol/src/NetIOBusinessData.cpp.i:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/src/NetIOBusinessData.cpp.i
.PHONY : protocol/src/NetIOBusinessData.cpp.i

protocol/src/NetIOBusinessData.s: protocol/src/NetIOBusinessData.cpp.s

.PHONY : protocol/src/NetIOBusinessData.s

# target to generate assembly for a file
protocol/src/NetIOBusinessData.cpp.s:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/src/NetIOBusinessData.cpp.s
.PHONY : protocol/src/NetIOBusinessData.cpp.s

protocol/test/NetTest.obj: protocol/test/NetTest.cpp.obj

.PHONY : protocol/test/NetTest.obj

# target to build an object file
protocol/test/NetTest.cpp.obj:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/test/NetTest.cpp.obj
.PHONY : protocol/test/NetTest.cpp.obj

protocol/test/NetTest.i: protocol/test/NetTest.cpp.i

.PHONY : protocol/test/NetTest.i

# target to preprocess a source file
protocol/test/NetTest.cpp.i:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/test/NetTest.cpp.i
.PHONY : protocol/test/NetTest.cpp.i

protocol/test/NetTest.s: protocol/test/NetTest.cpp.s

.PHONY : protocol/test/NetTest.s

# target to generate assembly for a file
protocol/test/NetTest.cpp.s:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/test/NetTest.cpp.s
.PHONY : protocol/test/NetTest.cpp.s

protocol/test/serializationTest.obj: protocol/test/serializationTest.cpp.obj

.PHONY : protocol/test/serializationTest.obj

# target to build an object file
protocol/test/serializationTest.cpp.obj:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/test/serializationTest.cpp.obj
.PHONY : protocol/test/serializationTest.cpp.obj

protocol/test/serializationTest.i: protocol/test/serializationTest.cpp.i

.PHONY : protocol/test/serializationTest.i

# target to preprocess a source file
protocol/test/serializationTest.cpp.i:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/test/serializationTest.cpp.i
.PHONY : protocol/test/serializationTest.cpp.i

protocol/test/serializationTest.s: protocol/test/serializationTest.cpp.s

.PHONY : protocol/test/serializationTest.s

# target to generate assembly for a file
protocol/test/serializationTest.cpp.s:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/protocol/test/serializationTest.cpp.s
.PHONY : protocol/test/serializationTest.cpp.s

server/test/client/SimpleClient.obj: server/test/client/SimpleClient.cpp.obj

.PHONY : server/test/client/SimpleClient.obj

# target to build an object file
server/test/client/SimpleClient.cpp.obj:
	$(MAKE) -f CMakeFiles\space_battle_server_test.dir\build.make CMakeFiles/space_battle_server_test.dir/server/test/client/SimpleClient.cpp.obj
.PHONY : server/test/client/SimpleClient.cpp.obj

server/test/client/SimpleClient.i: server/test/client/SimpleClient.cpp.i

.PHONY : server/test/client/SimpleClient.i

# target to preprocess a source file
server/test/client/SimpleClient.cpp.i:
	$(MAKE) -f CMakeFiles\space_battle_server_test.dir\build.make CMakeFiles/space_battle_server_test.dir/server/test/client/SimpleClient.cpp.i
.PHONY : server/test/client/SimpleClient.cpp.i

server/test/client/SimpleClient.s: server/test/client/SimpleClient.cpp.s

.PHONY : server/test/client/SimpleClient.s

# target to generate assembly for a file
server/test/client/SimpleClient.cpp.s:
	$(MAKE) -f CMakeFiles\space_battle_server_test.dir\build.make CMakeFiles/space_battle_server_test.dir/server/test/client/SimpleClient.cpp.s
.PHONY : server/test/client/SimpleClient.cpp.s

server/test/simple_test.obj: server/test/simple_test.cpp.obj

.PHONY : server/test/simple_test.obj

# target to build an object file
server/test/simple_test.cpp.obj:
	$(MAKE) -f CMakeFiles\space_battle_server_test.dir\build.make CMakeFiles/space_battle_server_test.dir/server/test/simple_test.cpp.obj
.PHONY : server/test/simple_test.cpp.obj

server/test/simple_test.i: server/test/simple_test.cpp.i

.PHONY : server/test/simple_test.i

# target to preprocess a source file
server/test/simple_test.cpp.i:
	$(MAKE) -f CMakeFiles\space_battle_server_test.dir\build.make CMakeFiles/space_battle_server_test.dir/server/test/simple_test.cpp.i
.PHONY : server/test/simple_test.cpp.i

server/test/simple_test.s: server/test/simple_test.cpp.s

.PHONY : server/test/simple_test.s

# target to generate assembly for a file
server/test/simple_test.cpp.s:
	$(MAKE) -f CMakeFiles\space_battle_server_test.dir\build.make CMakeFiles/space_battle_server_test.dir/server/test/simple_test.cpp.s
.PHONY : server/test/simple_test.cpp.s

server/test/test_main.obj: server/test/test_main.cpp.obj

.PHONY : server/test/test_main.obj

# target to build an object file
server/test/test_main.cpp.obj:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/server/test/test_main.cpp.obj
.PHONY : server/test/test_main.cpp.obj

server/test/test_main.i: server/test/test_main.cpp.i

.PHONY : server/test/test_main.i

# target to preprocess a source file
server/test/test_main.cpp.i:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/server/test/test_main.cpp.i
.PHONY : server/test/test_main.cpp.i

server/test/test_main.s: server/test/test_main.cpp.s

.PHONY : server/test/test_main.s

# target to generate assembly for a file
server/test/test_main.cpp.s:
	$(MAKE) -f CMakeFiles\protocole_test.dir\build.make CMakeFiles/protocole_test.dir/server/test/test_main.cpp.s
.PHONY : server/test/test_main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... googletest
	@echo ... space_battle_server_test
	@echo ... rebuild_cache
	@echo ... protocole_test
	@echo ... edit_cache
	@echo ... external/googletest/googletest/src/gtest-all.obj
	@echo ... external/googletest/googletest/src/gtest-all.i
	@echo ... external/googletest/googletest/src/gtest-all.s
	@echo ... external/googletest/googletest/src/gtest_main.obj
	@echo ... external/googletest/googletest/src/gtest_main.i
	@echo ... external/googletest/googletest/src/gtest_main.s
	@echo ... protocol/src/Net.obj
	@echo ... protocol/src/Net.i
	@echo ... protocol/src/Net.s
	@echo ... protocol/src/NetIOBusinessData.obj
	@echo ... protocol/src/NetIOBusinessData.i
	@echo ... protocol/src/NetIOBusinessData.s
	@echo ... protocol/test/NetTest.obj
	@echo ... protocol/test/NetTest.i
	@echo ... protocol/test/NetTest.s
	@echo ... protocol/test/serializationTest.obj
	@echo ... protocol/test/serializationTest.i
	@echo ... protocol/test/serializationTest.s
	@echo ... server/test/client/SimpleClient.obj
	@echo ... server/test/client/SimpleClient.i
	@echo ... server/test/client/SimpleClient.s
	@echo ... server/test/simple_test.obj
	@echo ... server/test/simple_test.i
	@echo ... server/test/simple_test.s
	@echo ... server/test/test_main.obj
	@echo ... server/test/test_main.i
	@echo ... server/test/test_main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

